spring:
  datasource:
    password: Lenkeran5566
    username: root
    url: jdbc:mysql://localhost:3306/bank_release1

  liquibase:
    change-log: classpath:/liquibase/changelog-master.yml
    drop-first: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: riyadrahimov28@gmail.com
    password: 'epad qsqm erdr oupy'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: 5c32083d4a3dc3686ec57373b2f1f240dd0f693abff056b0637088e1e2ae9ce2
  access-expiration: 900000
  refresh-expiration: 604800000

